### ISSUE TITLE
plotting function

### ISSUE THREAD

**Issue by Farhad63** [dportik/moments_pipeline#1]
Hi Daniel
Thanks, this is great.
I wonder if you have updated plotting function (Plotting_Functions.py) for moments.

**Comment by dportik** [comment]
Hello,
I am not sure I understand what you are referring to here. Could you be more specific if there is an issue, or more specific about a feature request?

**Comment by Farhad63** [comment]
Hello and thank you for the reply
I am just wondering if you also have the script file for plotting the model in moments similar to the one you have written for dadi _pipline (Plotting_Function in dadi_pipline).

**Comment by dportik** [comment]
I unfortunately did not create a script for that, and will not likely create one for this pipeline. You may be able to do some basic plotting following the manual, once you have the optimized parameters for your model.
