### ISSUE TITLE
3 population models?

### ISSUE THREAD

**Issue by r-catullo** [dportik/moments_pipeline#2]
Hi Dan,

Sorry to load this as an issue but the moments main page suggested emailing you for 3 population models. But your current contact details are very hard to find! I was wondering if you could email me about them? We are working on running them and would love to see anything you've done to convert the dadi 3D models to a moments version.

Thanks,

Renee (renee.catullo@uwa.edu.au)

**Comment by dportik** [comment]
Hi @r-catullo,
I did not end up making any 3D versions of this pipeline, and my development on this has stopped. My recommendation is to try and look at the conversion of 2D models from dadi to moments and try to replicate that for the 3D models.
